// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YadSara.Data;

#nullable disable

namespace YadSara.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("YadSara.Core.Entities.Borrow", b =>
                {
                    b.Property<string>("borrowId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("borrowName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("cityId")
                        .HasColumnType("int");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("borrowId");

                    b.ToTable("Borrow");

                    b.HasData(
                        new
                        {
                            borrowId = "246987569",
                            address = "Rabbi Akiva",
                            borrowName = "yosiLev",
                            cityId = 1,
                            phone = "0556987459"
                        });
                });

            modelBuilder.Entity("YadSara.Core.Entities.City", b =>
                {
                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CityId");

                    b.ToTable("City");

                    b.HasData(
                        new
                        {
                            CityId = 1,
                            CityName = "בני ברק"
                        });
                });

            modelBuilder.Entity("YadSara.Core.Entities.Equipment", b =>
                {
                    b.Property<int>("idEquipment")
                        .HasColumnType("int");

                    b.Property<int>("currentquantity")
                        .HasColumnType("int");

                    b.Property<string>("deposit")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("lenderId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("nameEquipment")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("nameEquipmentck")
                        .HasColumnType("int");

                    b.HasKey("idEquipment");

                    b.ToTable("Equipment");

                    b.HasData(
                        new
                        {
                            idEquipment = 1,
                            currentquantity = 2,
                            deposit = "צק פיקדון",
                            lenderId = "254698745",
                            nameEquipment = "מחולל חמצן",
                            nameEquipmentck = 5
                        });
                });

            modelBuilder.Entity("YadSara.Core.Entities.Lender", b =>
                {
                    b.Property<string>("lenderId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("lenderAdress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("lenderCityId")
                        .HasColumnType("int");

                    b.Property<string>("lenderName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("lenderPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("lenderId");

                    b.ToTable("Lender");

                    b.HasData(
                        new
                        {
                            lenderId = "254698743",
                            lenderAdress = "Rabbi Akiva",
                            lenderCityId = 1,
                            lenderName = "david",
                            lenderPhone = "0556987459"
                        });
                });

            modelBuilder.Entity("YadSara.Core.Entities.Lending", b =>
                {
                    b.Property<int>("LendingId")
                        .HasColumnType("int");

                    b.Property<int>("IdEquipment")
                        .HasColumnType("int");

                    b.Property<bool>("IsReturned")
                        .HasColumnType("bit");

                    b.Property<DateTime>("TimeLending")
                        .HasColumnType("datetime2");

                    b.Property<string>("borrowId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("deadlineLending")
                        .HasColumnType("datetime2");

                    b.Property<string>("lenderId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("LendingId");

                    b.ToTable("Lending");

                    b.HasData(
                        new
                        {
                            LendingId = 1,
                            IdEquipment = 1,
                            IsReturned = false,
                            TimeLending = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            borrowId = "246987569",
                            deadlineLending = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            lenderId = "254698743"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
