<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\YadSara.Core\YadSara.Core.csproj" />
    <ProjectReference Include="..\YadSara.Data\YadSara.Data.csproj" />
    <ProjectReference Include="..\YadSara.Service\YadSara.Service.csproj" />
  </ItemGroup>

</Project>
